name: GitHub Actions Demo
on: [push]
jobs:
  mail_on_push:
    runs-on: ubuntu-latest
    steps:
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Email sending 
        body: ${{github.event.head_commit.message}} pushed from ${{github.repository}}
        to: livia.janson@gmail.com
        from: Livia Janson

 